.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 3/30/10               \" DATE 
.Dt pdf-splitter 1      \" Program name and manual section number 
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify 
.Nm pdf-splitter
.\" The following lines are read in generating the apropos(man -k) database. Use only key
.\" words here as the database is built based on the words here and in the .ND line. 
.\" Use .Nm macro to designate other names for the documented program.
.Nd Split PDF files into image files for OCR or web page images.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm 
.Op Ar file              \" [file]
.Op Ar output
.Ar width
.Ar format
.Sh DESCRIPTION          \" Section Header - required - don't modify

.Nm pdf-splitter
will split your pdf files and output page images using native cocoa libraries for speed and memory management. 
It requires each of the following arguments:
.Pp                      \" Inserts a space
.Bl -tag -width -indent  \" Begins a tagged list 
.It file               \" Each item preceded by .It macro
An input file in pdf format.
.It output
The directory in which to store the files as 1.format, 2.format etc. It will be created if necessary.
.It width
The width of the output images.
.It format
An image format, currently tif, jpg, png, gif, png, and jpeg2000 are supported.
.El                      \" Ends the list
.Pp

.\" .Sh ENVIRONMENT      \" May not be needed
.\" .Bl -tag -width "ENV_VAR_1" -indent \" ENV_VAR_1 is width of the string ENV_VAR_1
.\" .It Ev ENV_VAR_1
.\" Description of ENV_VAR_1
.\" .It Ev ENV_VAR_2
.\" Description of ENV_VAR_2
.\" .El                      
.\".Sh FILES                \" File used or created by the topic of the man page
.\".Bl -tag -width "/Users/joeuser/Library/really_long_file_name" -compact
.\".It Pa /usr/share/file_name
.\"FILE_1 description
.\".It Pa /Users/joeuser/Library/really_long_file_name
.\"FILE_2 description
.\".El                      \" Ends the list
.\" .Sh DIAGNOSTICS       \" May not be needed
.\" .Bl -diag
.\" .It Diagnostic Tag
.\" Diagnostic informtion here.
.\" .It Diagnostic Tag
.\" Diagnostic informtion here.
.\" .El
.Sh SEE ALSO 
.\" List links in ascending order by section, alphabetically within a section.
.\" Please do not reference files that do not exist without filing a bug report
.Xr sips 1
.\" .Sh BUGS              \" Document known, unremedied bugs 
.\" .Sh HISTORY           \" Document history if command behaves in a unique manner